# Generated by Django 3.2.9 on 2021-11-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('picture', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('width', models.PositiveIntegerField(blank=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, verbose_name='Высота')),
                ('parent_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='images.images', verbose_name='Родительское изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['pk'],
            },
        ),
    ]
